apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-spring-boot
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: docker-spring-boot
    spec:
      containers:
        - name: docker-spring-boot
          image: gcr.io/internal-investment-206615/docker-spring-boot
          ports:
            - containerPort: 8085